### PR TITLE
Refactor to handle different sorting orders

### PR DESCRIPTION
**Pull request by letroot**
Add a default arg as flag to change the sorting order.

### CODE REVIEW

**Comment by nnamdiib** [comment]
Nice. the Lambda part was cool too. 
But I have read in numerous places that if you have to assign a name to a Lambda, just use a def instead.
Using defs will achieve the same goal, with the added bonus of flexibility.
What dost thou think?

**Comment by letroot** [comment]
The idea of using named lambdas isn't so much about flexibilty as it is about concerns over readability as raised in the Zen of Python.  Guido van Rossum frowns at even the most basic func prog constructs, he even relegated reduce to the `functools` module...go figure.

Well in this code piece, we are not sacrificing readabilty at all as what we have is a one-liner that does just one thing - compare and return a boolean.

To zone in on the concern of flexibility, lambdas in Python are lame, lame as in on crutches with a twisted ankle lame! The body of a Python `lambda`can only consist of an expression! Not even statements or multiple expressions are valid. Basically, just one thing (Guido strikes again).

Lambdas are indeed not flexible, but in our code, we need this inflexibility or at least it's terse enough to be readable and the `compare` functionality is not a moving target that we need to build flexibility into.

So yeah in all, it's safe to leave the lambda there. :)

**Comment by nnamdiib** [comment]
Okay okay. Will merge it then. 

Thanks for your help!

lol this was productive. Lets do more.

**Comment by letroot** [comment]
Yup! Would love that.

So commit more code...

**Pull request merged**
